// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type MutationReply struct {
	Msg string `json:"msg"`
}

type Puzzle struct {
	ID         string `json:"id"`
	Fen        string `json:"fen"`
	Moves      string `json:"moves"`
	Rating     int32  `json:"rating"`
	Popularity int32  `json:"popularity"`
	Themes     string `json:"themes"`
}

type PuzzleInput struct {
	Limit int32  `json:"limit"`
	Room  string `json:"room"`
}

type Query struct {
}

type Subscription struct {
}
