package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"app/chess/graph/model"
	"context"
	"fmt"
)

// GetPuzzles is the resolver for the GetPuzzles field.
func (r *mutationResolver) GetPuzzles(ctx context.Context, input model.PuzzleInput) (*model.MutationReply, error) {
	panic(fmt.Errorf("not implemented: GetPuzzles - GetPuzzles"))
}

// InitPuzzles is the resolver for the initPuzzles field.
func (r *queryResolver) InitPuzzles(ctx context.Context, input model.PuzzleInput) ([]*model.Puzzle, error) {
	panic(fmt.Errorf("not implemented: InitPuzzles - initPuzzles"))
}

// LatestPuzzles is the resolver for the latestPuzzles field.
func (r *subscriptionResolver) LatestPuzzles(ctx context.Context, input model.PuzzleInput) (<-chan []*model.Puzzle, error) {
	panic(fmt.Errorf("not implemented: LatestPuzzles - latestPuzzles"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
